#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# add extend memory
export NODE_OPTIONS="--max-old-space-size=8192"

npm run precommit ||
(
        echo '🔧🔨 ESLint Check Failed. Please check the output above for specific issues. 🔧🔨'
        false; 
)


# Check Testing Standards
# npm run test ||
# (
#         echo '🔧🔨 Testing Failed. Make the required changes listed above, add changes and try to commit again. 🔧🔨'
#         false; 
# )

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# npm run build ||
# (
#     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#             Next build failed: View the errors above to see why. 
#     '
#     false;
# )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
