#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# add extend memory
export NODE_OPTIONS="--max-old-space-size=8192"

bun lint-staged

# Check Testing Standards
# bun test ||
# (
#   echo 'Testing Failed. Make the required changes listed above, add changes and try to commit again. 🔧🔨'
#      false; 
# )

# If everything passes... Now we can commit
echo 'Alright... Code looks good to me... Trying to build now'

bun run build ||
(
    echo 'Next build failed: View the errors above to see why.'
    false;
)

# If everything passes... Now we can commit
echo 'Commit Successful 🎉🎉🎉'
